# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@angular/common-8.0.3" = {
      name = "_at_angular_slash_common";
      packageName = "@angular/common";
      version = "8.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@angular/common/-/common-8.0.3.tgz";
        sha512 = "2YLYGVUf9eJZcocRmD3/9UHj4qFHt2t4ftDWJmrFM9zo2PZF+G5O9fASO7qoBbwpx3KFZtQO4dprKl2dFugRjg==";
      };
    };
    "@angular/compiler-8.0.3" = {
      name = "_at_angular_slash_compiler";
      packageName = "@angular/compiler";
      version = "8.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@angular/compiler/-/compiler-8.0.3.tgz";
        sha512 = "1/vF8D6l1O6IfWiDtaj6nC+B8CtkVtFgXgooDzLBO6XAkaCuJCnhKT1HnpWG5GtVsGaY9MGoTl1vE9ZMDbRQjg==";
      };
    };
    "@angular/core-8.0.3" = {
      name = "_at_angular_slash_core";
      packageName = "@angular/core";
      version = "8.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@angular/core/-/core-8.0.3.tgz";
        sha512 = "IIxrtIPNuv2+HudER9J1nmPGiGJ4aRpeiFM9V4lSiSFv50RzuaoG60XqYIpUyuBdgvyKigcrfSbu9+x1vyN0hw==";
      };
    };
    "@angular/forms-8.0.3" = {
      name = "_at_angular_slash_forms";
      packageName = "@angular/forms";
      version = "8.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@angular/forms/-/forms-8.0.3.tgz";
        sha512 = "22s82QDRQ72K4vMYuNh3NAN+da9uanwoydnfKlp2rb9dZAb2QVX9NN6gSoMrkSSr2O9KTP6pWiw6A3/MW8sGRA==";
      };
    };
    "@angular/platform-browser-8.0.3" = {
      name = "_at_angular_slash_platform-browser";
      packageName = "@angular/platform-browser";
      version = "8.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@angular/platform-browser/-/platform-browser-8.0.3.tgz";
        sha512 = "ceAPP2Ijmk2sZ1rnOU/WNlE3DtT6K6ljpjO9oUfXKMoSMdWirJKAraT3m/BAzmYwMSXpPBxA7c3paZjiLL6t5A==";
      };
    };
    "@angular/platform-browser-dynamic-8.0.3" = {
      name = "_at_angular_slash_platform-browser-dynamic";
      packageName = "@angular/platform-browser-dynamic";
      version = "8.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@angular/platform-browser-dynamic/-/platform-browser-dynamic-8.0.3.tgz";
        sha512 = "ZjQjSYslSQAKzM4llvyMFxnSjFpbhT1U9FOdKwscPe475zAKX0087qsHrP2CRwkJRfwtdcmj9wMUQIPlzMpHLA==";
      };
    };
    "@angular/router-8.0.3" = {
      name = "_at_angular_slash_router";
      packageName = "@angular/router";
      version = "8.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@angular/router/-/router-8.0.3.tgz";
        sha512 = "CU5pLTfQVUnTN93mdIKJrVjXiNldUkk30DPz4lpdxpZjYOqFGXeeSeQWmToHSofLPodNcAB4kkZ41VyXvlBu7w==";
      };
    };
    "@nornagon/put-0.0.8" = {
      name = "_at_nornagon_slash_put";
      packageName = "@nornagon/put";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nornagon/put/-/put-0.0.8.tgz";
        sha512 = "ugvXJjwF5ldtUpa7D95kruNJ41yFQDEKyF5CW4TgKJnh+W/zmlBzXXeKTyqIgwMFrkePN2JqOBqcF0M0oOunow==";
      };
    };
    "abstract-socket-2.1.1" = {
      name = "abstract-socket";
      packageName = "abstract-socket";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abstract-socket/-/abstract-socket-2.1.1.tgz";
        sha512 = "YZJizsvS1aBua5Gd01woe4zuyYBGgSMeqDOB6/ChwdTI904KP6QGtJswXl4hcqWxbz86hQBe++HWV0hF1aGUtA==";
      };
    };
    "bindings-1.5.0" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz";
        sha512 = "p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==";
      };
    };
    "dbus-next-0.8.2" = {
      name = "dbus-next";
      packageName = "dbus-next";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dbus-next/-/dbus-next-0.8.2.tgz";
        sha512 = "E2wkbhZzzsgmY+jxIdeuhA1nVT697I5koRIRJTk3doTeukwtzqSFG89RC5XK8OsLG/eHDZ8PVNptUuEPkhdPbA==";
      };
    };
    "duplexer-0.1.1" = {
      name = "duplexer";
      packageName = "duplexer";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer/-/duplexer-0.1.1.tgz";
        sha1 = "ace6ff808c1ce66b57d1ebf97977acb02334cfc1";
      };
    };
    "event-stream-3.3.4" = {
      name = "event-stream";
      packageName = "event-stream";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-stream/-/event-stream-3.3.4.tgz";
        sha1 = "4ab4c9a0f5a54db9338b4c34d86bfce8f4b35571";
      };
    };
    "file-uri-to-path-1.0.0" = {
      name = "file-uri-to-path";
      packageName = "file-uri-to-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz";
        sha512 = "0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==";
      };
    };
    "from-0.1.7" = {
      name = "from";
      packageName = "from";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/from/-/from-0.1.7.tgz";
        sha1 = "83c60afc58b9c56997007ed1a768b3ab303a44fe";
      };
    };
    "hexy-0.2.11" = {
      name = "hexy";
      packageName = "hexy";
      version = "0.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/hexy/-/hexy-0.2.11.tgz";
        sha512 = "ciq6hFsSG/Bpt2DmrZJtv+56zpPdnq+NQ4ijEFrveKN0ZG1mhl/LdT1NQZ9se6ty1fACcI4d4vYqC9v8EYpH2A==";
      };
    };
    "jsbi-2.0.5" = {
      name = "jsbi";
      packageName = "jsbi";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbi/-/jsbi-2.0.5.tgz";
        sha512 = "TzO/62Hxeb26QMb4IGlI/5X+QLr9Uqp1FPkwp2+KOICW+Q+vSuFj61c8pkT6wAns4WcK56X7CmSHhJeDGWOqxQ==";
      };
    };
    "long-4.0.0" = {
      name = "long";
      packageName = "long";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/long/-/long-4.0.0.tgz";
        sha512 = "XsP+KhQif4bjX1kbuSiySJFNAehNxgLb6hPRGJ9QsUr8ajHkuXGdrHmFUTUUXhDwVX2R5bY4JNZEwbUiMhV+MA==";
      };
    };
    "map-stream-0.1.0" = {
      name = "map-stream";
      packageName = "map-stream";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-stream/-/map-stream-0.1.0.tgz";
        sha1 = "e56aa94c4c8055a16404a0674b78f215f7c8e194";
      };
    };
    "nan-2.14.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.14.0.tgz";
        sha512 = "INOFj37C7k3AfaNTtX8RhsTw7qRy7eLET14cROi9+5HAVbbHuIWUHEauBv5qT4Av2tWasiTY1Jw6puUNqRJXQg==";
      };
    };
    "node-addon-api-1.7.1" = {
      name = "node-addon-api";
      packageName = "node-addon-api";
      version = "1.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-addon-api/-/node-addon-api-1.7.1.tgz";
        sha512 = "2+DuKodWvwRTrCfKOeR24KIc5unKjOh8mz17NCzVnHWfjAdDqbfbjqh7gUT+BkXBRQM52+xCHciKWonJ3CbJMQ==";
      };
    };
    "pause-stream-0.0.11" = {
      name = "pause-stream";
      packageName = "pause-stream";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/pause-stream/-/pause-stream-0.0.11.tgz";
        sha1 = "fe5a34b0cbce12b5aa6a2b403ee2e73b602f1445";
      };
    };
    "rxjs-6.4.0" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-6.4.0.tgz";
        sha512 = "Z9Yfa11F6B9Sg/BK9MnqnQ+aQYicPLtilXBp2yUtDt2JRCE0h26d33EnfO3ZxoNxG0T92OUucP3Ct7cpfkdFfw==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "split-0.3.3" = {
      name = "split";
      packageName = "split";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-0.3.3.tgz";
        sha1 = "cd0eea5e63a211dfff7eb0f091c4133e2d0dd28f";
      };
    };
    "stream-combiner-0.0.4" = {
      name = "stream-combiner";
      packageName = "stream-combiner";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-combiner/-/stream-combiner-0.0.4.tgz";
        sha1 = "4d5e433c185261dde623ca3f44c586bcf5c4ad14";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "tslib-1.10.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.10.0.tgz";
        sha512 = "qOebF53frne81cf0S9B41ByenJ3/IuH8yJKngAX35CmiZySA0khhkovshKK+jGCaMnVomla7gVlIcc3EvKPbTQ==";
      };
    };
    "xml2js-0.4.19" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.19.tgz";
        sha512 = "esZnJZJOiJR9wWKMyuvSE1y6Dq5LCuJanqhxslH2bxM6duahNZ+HMpCLhBQGZkbX6xRf8x1Y2eJlgt2q3qo49Q==";
      };
    };
    "xmlbuilder-9.0.7" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "9.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-9.0.7.tgz";
        sha1 = "132ee63d2ec5565c557e20f4c22df9aca686b10d";
      };
    };
    "zone.js-0.9.1" = {
      name = "zone.js";
      packageName = "zone.js";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/zone.js/-/zone.js-0.9.1.tgz";
        sha512 = "GkPiJL8jifSrKReKaTZ5jkhrMEgXbXYC+IPo1iquBjayRa0q86w3Dipjn8b415jpitMExe9lV8iTsv8tk3DGag==";
      };
    };
  };
  args = {
    name = "tuxedo-control-center";
    packageName = "tuxedo-control-center";
    version = "1.0.14";
    src = ./.;
    dependencies = [
      sources."@angular/common-8.0.3"
      sources."@angular/compiler-8.0.3"
      sources."@angular/core-8.0.3"
      sources."@angular/forms-8.0.3"
      sources."@angular/platform-browser-8.0.3"
      sources."@angular/platform-browser-dynamic-8.0.3"
      sources."@angular/router-8.0.3"
      sources."@nornagon/put-0.0.8"
      sources."abstract-socket-2.1.1"
      sources."bindings-1.5.0"
      sources."dbus-next-0.8.2"
      sources."duplexer-0.1.1"
      sources."event-stream-3.3.4"
      sources."file-uri-to-path-1.0.0"
      sources."from-0.1.7"
      sources."hexy-0.2.11"
      sources."jsbi-2.0.5"
      sources."long-4.0.0"
      sources."map-stream-0.1.0"
      sources."nan-2.14.0"
      sources."node-addon-api-1.7.1"
      sources."pause-stream-0.0.11"
      sources."rxjs-6.4.0"
      sources."safe-buffer-5.1.2"
      sources."split-0.3.3"
      sources."stream-combiner-0.0.4"
      sources."through-2.3.8"
      sources."tslib-1.10.0"
      (sources."xml2js-0.4.19" // {
        dependencies = [
          sources."sax-1.2.4"
        ];
      })
      sources."xmlbuilder-9.0.7"
      sources."zone.js-0.9.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      homepage = "https://tuxedocomputers.com";
      license = "GPL-3.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
